### ISSUE TITLE
Running Jobs on Remote Resources with Pulsar - job_metrics_config_file option missing

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/ansible-pulsar#19]
During the 2021 Galaxy Admin Training:
```
Jan 28 10:18:07 gat-3.eu.training.galaxyproject.eu uwsgi[1702841]: FileNotFoundError: [Errno 2] No such file or directory: ‘/srv/galaxy/jobs/000/30/__instrument_hostname_hostname’
```
This happens because the `job_metrics_config_file` option is not present in the Pulsar configuration.
Pulsar needs to know which metrics Galaxy is expecting to receive

**Comment by natefoo** [comment]
@hexylena it's a list in the Pulsar role so that it's ordered - what's the rationale for making it a dict?

**Comment by hexylena** [comment]
uhh didn't mean dict I guess, I just want to use the same variable between galaxy/pulsar.

**Comment by natefoo** [comment]
This is now possible as of #20 in both the `galaxyproject.galaxy` and `galaxyproject.pulsar` roles using `galaxy_job_metrics_plugins` and `pulsar_job_metrics_plugins`:

```yaml
pulsar_job_metrics_plugins:
  - type: core
  - type: cpuinfo
    verbose: true
  - type: meminfo
  - type: uname
  - type: cgroup
```

Setting `*_job_metrics_plugins` sets the Galaxy/Pulsar config file's `job_metrics_config_file` option accordingly. The syntax is Galaxy's semi-standard `plugin_config` format which is shown for dependency resolvers [in the 21.09+ documentation](https://docs.galaxyproject.org/en/latest/admin/dependency_resolvers.html) (but this has been supported from earlier releases).
